language: python
python:
  - "2.7"
install:
  - "sudo apt-get install python-scipy"
  - "sudo apt-get install python-matplotlib"
  - "pip install pyrex"
  - "cd include && python gauss_setup.py build_ext && cd .."
script: "python app.py test"