language: python
python:
  - "2.7"
install:
  - "sudo apt-get install python-matplotlib"
  - "sudo apt-get build-dep python-scipy"
  - "pip install scipy"
  - "pip install pyrex"
  - "cd include && python gauss_setup.py build_ext install && cd .."
script: "python app.py test"